#!/usr/bin/env node

let fs ;
let childProcessExec;
let util;

const isCJS = typeof module !== 'undefined' && module.exports;

console.log(`\n\x1b[33mExecuting pre-commit hook under ${isCJS ? 'CJS' : 'ESM'} engine`);

async function loadModules() {

  if (isCJS) {
      fs = require('fs');
      childProcessExec = require("child_process").exec;
      util = require("util");
  } else {
      fs = await import('fs').then(module => module.default);
      childProcessExec = await import("child_process").then(module => module.default.exec);
      util = await import('util').then(module => module.default);

      console.log(childProcessExec)
  }
}

const validatePreCommit = async () => {
  await loadModules();

  const exec = util.promisify(childProcessExec);

  const staggedFiles = await exec("git diff --cached --name-only");

  const staggedFilesWithJsOrTs = staggedFiles.stdout
    .split("\n")
    .filter(
      (staggedFile) =>
        staggedFile.endsWith(".js") || staggedFile.endsWith(".ts")
    );

  staggedFilesWithJsOrTs.forEach((staggedFile) => {
    const readFile = fs.readFileSync(staggedFile, "utf8").trim();

    if (readFile.includes("console.log")) {
      console.log(
        `\n\x1b[31mCOMMIT REJECTED!  Found console references in ${staggedFile}. Please remove them before committing.\n`
      );
      process.exit(1);
    }

    if (readFile.includes("debugger")) {
      console.log(
        `\n\x1b[31mCOMMIT REJECTED!  Found debugger references in ${staggedFile}. Please remove them before committing.\n`
      );
      process.exit(1);
    }
  });

  console.log("\n\x1b[32mNo console. or debugger references found!\n");
  console.log("\x1b[32mGit pre-commit hook was successful!\n");

  process.exit(0);
};

validatePreCommit();
